#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-mockr
Version  : 0.2.2
Release  : 44
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/mockr_0.2.2.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/mockr_0.2.2.tar.gz
Summary  : Mocking in R
Group    : Development/Tools
License  : MIT
Requires: R-rlang
Requires: R-withr
BuildRequires : R-rlang
BuildRequires : R-withr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
temporarily substitute it for testing. Designed as a drop-in

%prep
%setup -q -n mockr
pushd ..
cp -a mockr buildavx2
popd
pushd ..
cp -a mockr buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746133695

%install
export SOURCE_DATE_EPOCH=1746133695
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mockr/DESCRIPTION
/usr/lib64/R/library/mockr/INDEX
/usr/lib64/R/library/mockr/LICENSE
/usr/lib64/R/library/mockr/Meta/Rd.rds
/usr/lib64/R/library/mockr/Meta/features.rds
/usr/lib64/R/library/mockr/Meta/hsearch.rds
/usr/lib64/R/library/mockr/Meta/links.rds
/usr/lib64/R/library/mockr/Meta/nsInfo.rds
/usr/lib64/R/library/mockr/Meta/package.rds
/usr/lib64/R/library/mockr/Meta/vignette.rds
/usr/lib64/R/library/mockr/NAMESPACE
/usr/lib64/R/library/mockr/NEWS.md
/usr/lib64/R/library/mockr/R/mockr
/usr/lib64/R/library/mockr/R/mockr.rdb
/usr/lib64/R/library/mockr/R/mockr.rdx
/usr/lib64/R/library/mockr/doc/index.html
/usr/lib64/R/library/mockr/doc/mockr.R
/usr/lib64/R/library/mockr/doc/mockr.Rmd
/usr/lib64/R/library/mockr/doc/mockr.html
/usr/lib64/R/library/mockr/help/AnIndex
/usr/lib64/R/library/mockr/help/aliases.rds
/usr/lib64/R/library/mockr/help/mockr.rdb
/usr/lib64/R/library/mockr/help/mockr.rdx
/usr/lib64/R/library/mockr/help/paths.rds
/usr/lib64/R/library/mockr/html/00Index.html
/usr/lib64/R/library/mockr/html/R.css
/usr/lib64/R/library/mockr/tests/testthat.R
/usr/lib64/R/library/mockr/tests/testthat/test-mock.R
